### ISSUE TITLE
Able to scroll vertically on MacOS (rubber band)

### ISSUE THREAD

**Issue by alii** [revoltchat/desktop#41]
Likely fix is adding the following css

```css
body {
	overflow-y: hidden;
}
```

Video:
https://user-images.githubusercontent.com/25351731/139604733-af3a1aab-589c-4228-a661-f1fe160e8404.mov
